from app.bootstrap_paths import bootstrap_repo_paths

bootstrap_repo_paths()

from ev_core.contracts.requests import ExternalChargingRequest
from ev_core.contracts.responses import RecommendationResponse

RecommendationRequest = ExternalChargingRequest
RecommendationsResponse = RecommendationResponse